### ISSUE TITLE
Builds originels décalés de 2 pixels

### ISSUE THREAD

**Issue by Nicofuma** [CorentinGC/reddit-place-kcorp#10]
Tous les builds d'origine (arc de triomphe, dofus, croissant) sont décalés de 2 pixels vers le bas et et vers la droite.
Ca rend la correction de certains amongus compliquée.

**Comment by Thiryn** [comment]
![image](https://user-images.githubusercontent.com/1838835/161547209-6ed43e2d-52a5-4c38-ac55-2a9ec3e93265.png)
![image](https://user-images.githubusercontent.com/1838835/161547225-7c1e095a-0be4-4bb4-9d8d-7bacee2aa4b5.png)
