### ISSUE TITLE
Discord ?

### ISSUE THREAD

**Issue by egeant94** [CorentinGC/reddit-place-kcorp#14]
J'aimerai bien aider avec les pushs, n'hesitez pas a partager un discord ou autre pour s'organiser.

**Comment by CorentinGC** [comment]
Stream: https://www.twitch.tv/kamet0
Discord: https://discord.gg/kameto

**Comment by egeant94** [comment]
La jinx n'a toujours pas la bonne palette de couleur non plus, j'aimerai bien aider avec une pull request mais vu que vous répondez pas :/
