### ISSUE TITLE
Proposition Rayman (alentours position (55,1600))

### ISSUE THREAD

**Issue by Tamos40000** [CorentinGC/reddit-place-kcorp#22]
![Rayman](https://user-images.githubusercontent.com/102991533/161606863-0946a170-a7f1-4cb1-be55-a1184ebd29e6.png)

**Comment by letrucquitue** [comment]
On avait pour idée de refaire celui de tout à l'heure (j'en ai discuté avec la commu Rayman)
![rayman](https://user-images.githubusercontent.com/17125767/161623065-f192667f-1632-4104-b211-22f959e16091.png)
A voir si les devs ont le temps de l'ajouter mais ça serait cool (bon courage à vous très bon travail btw)

**Comment by letrucquitue** [comment]
OMG VOUS L'AVEZ MIS MERCI BEAUCOUP ! La commu Rayman est très contente merci !
