### ISSUE TITLE
Couleurs incorrectes

### ISSUE THREAD

**Issue by MichelSama** [CorentinGC/reddit-place-kcorp#23]
Les couleurs de Jinx et des Daft Punk ne sont pas dans la bonne palette, du coup c'est pour ça que tout le monde galère.

**Comment by Noxionx** [comment]
La color palette :
#6D001A,
#BE0039,
#FF4500,
#FFA800,
#FFD635,
#FFF8B8,
#00A368,
#00CC78,
#7EED56,
#00756F,
#009EAA,
#00CCC0,
#2450A4,
#3690EA,
#51E9F4,
#493AC1,
#6A5CFF,
#94B3FF,
#811E9F,
#B44AC0,
#E4ABFF,
#DE107F,
#FF3881,
#FF99AA,
#6D482F,
#9C6926,
#FFB470,
#000000,
#515252,
#898D90,
#D4D7D9

**Comment by CorentinGC** [comment]
Ouaip on a eu des galères :/
On avait un tool qui gérait ca, mais notre image de base avait des problèmes (je crois), et on avait pas d'autres version, du coup on à laissé comme ca ><
